/*
 * @filename : Define.h
 * @author   : Hao Limin
 * @date     : 2020-06-08
 * @email    : haolimin01@sjtu.edu.cn
 */

#ifndef NETLISTVIZ_DEFINE_DEFINE_H
#define NETLISTVIZ_DEFINE_DEFINE_H

#include <cassert>

/* For trace and debug */
#define LINE_INFO "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "() ] - "


/* unused param */
#define UNUSED(x) (void*)x


/* Disallow copy and assign functions that generated by compiler. */
#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
    TypeName(const TypeName &);            \
    TypeName &operator=(const TypeName &)

#ifndef NOT
#define NOT !
#endif

#ifndef AND
#define AND &&
#endif

/* exit */
#define EXIT exit(1)

/* return status */
#define OKAY  0
#define ERROR 1

/* SchematicScene */
const int StartX = 600;
const int StartY = 600;
const int Width  = 1200;
const int Height = 900;
const int CenterX = StartX + Width / 4;
const int CenterY = StartY + Height / 4;

#endif //NETLISTVIZ_DEFINE_DEFINE_H
