/*
 * @filename : Define.h
 * @author   : Hao Limin
 * @date     : 2020-06-08
 * @email    : haolimin01@sjtu.edu.cn
 */

#ifndef NETLISTVIZ_DEFINE_DEFINE_H
#define NETLISTVIZ_DEFINE_DEFINE_H

#include <cassert>

/* For trace and debug */
#define LINE_INFO "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "() ] - "


/* Disallow copy and assign functions that generated by compiler. */
#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
    TypeName(const TypeName &);            \
    TypeName &operator=(const TypeName &)

#ifndef NOT
#define NOT !
#endif

#ifndef AND
#define AND &&
#endif

/* exit */
#define EXIT exit(1)

/* return status */
#define OKAY  0
#define ERROR 1

/* For Scene */
const static int Row_Device_Factor = 2;
const static int DFT_Grid_W = 50;
const static int DFT_Grid_H = 50;
const static int DFT_DIS = 15;
const static int Scene_Margin = 50;
const static int Scene_Available = 1250;
const static int Scene_W = Scene_Margin + 2 * Scene_Available;
const static int Scene_H = Scene_Margin + 2 * Scene_Available;

/* For SchematicWire */
const static int DFT_Wire_W = 2;

#endif //NETLISTVIZ_DEFINE_DEFINE_H
